name: HLPservices
favicon: null
layout_spectrum: 0.8848929654341191
typography_spectrum: 0.7462705448269844
title: HLP Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fce9fd'
    - '#aacfb0'
    - '#00100a'
    - '#69937b'
    - '#6b5e4d'
  brandStrength: 0.6875
  lightness: 0.9378682186361402
  saturation: 0.82023143209517
  rhythmicContrast: 0.25
purpose: []
