name: HLPservices
favicon: null
layout_spectrum: 0.8848929654341191
typography_spectrum: 0.7462705448269844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6848872303962708
  lightness: 0.9378682186361402
  saturation: 0.82023143209517
  rhythmicContrast: 0.1588702891021967
purpose: []
